version: '{build}'

skip_tags: true

environment:
  JAVA_HOME: '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home'

install:
  # Prepend Java entry to PATH
  - cmd: export PATH=$JAVA_HOME/bin:$PATH
  - cmd: export MAVEN_OPTS=-Xmx2g
  - cmd: export JAVA_OPTS=-Xmx2g
  - cmd: java -version
  # Set up toolchains for java and protoc
  - cmd: copy .appveyor/toolchains.xml ~/.m2/
  # Download all dependencies that integration tests might need later
  # These include protoc and grpc plugin executables being referenced in toolchains.xml
#  - cmd: mvnw.cmd -B -V -Dstyle.color=always -Djansi.passthrough=true dependency:go-offline -f src/it/dependencies/pom.xml -P protoc-3.4.0
  - cmd: mvnw.cmd -B -V -Dstyle.color=always -Djansi.passthrough=true dependency:go-offline -f src/it/dependencies/pom.xml -P protoc-3.12.0
  - cmd: mvnw.cmd -B -V -Dstyle.color=always -Djansi.passthrough=true dependency:go-offline -P run-its

build_script:
  - cmd: mvnw.cmd -B -V -Dstyle.color=always -Djansi.passthrough=true clean package -Dmaven.test.skip=true

test_script:
  - cmd: mvnw.cmd -B -V -Dstyle.color=always -Djansi.passthrough=true verify -P run-its -Dinvoker.streamLogs=true

cache:
  - '~/.m2/'
